In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("train.csv")

In [3]:
df = data.copy()

In [4]:
# df = data.copy()
y = df["SalePrice"]
x = df.drop(["SalePrice","Id"],axis= 1)

In [5]:
df.drop(["SalePrice","Id"],axis=1,inplace=True)

In [6]:
print(x)

      MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0             60       RL         65.0     8450   Pave   NaN      Reg
1             20       RL         80.0     9600   Pave   NaN      Reg
2             60       RL         68.0    11250   Pave   NaN      IR1
3             70       RL         60.0     9550   Pave   NaN      IR1
4             60       RL         84.0    14260   Pave   NaN      IR1
...          ...      ...          ...      ...    ...   ...      ...
1455          60       RL         62.0     7917   Pave   NaN      Reg
1456          20       RL         85.0    13175   Pave   NaN      Reg
1457          70       RL         66.0     9042   Pave   NaN      Reg
1458          20       RL         68.0     9717   Pave   NaN      Reg
1459          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub    Inside  ...           0        0    NaN    NaN
1            Lvl    AllPub       FR2  ...           0        0    NaN    NaN
2            Lvl    AllPub    Inside  ...           0        0    NaN    NaN
3            Lvl    AllPub    Corner  ...           0        0    NaN    NaN
4            Lvl    AllPub       FR2  ...           0        0    NaN    NaN
...          ...       ...       ...  ...         ...      ...    ...    ...
1455         Lvl    AllPub    Inside  ...           0        0    NaN    NaN
1456         Lvl    AllPub    Inside  ...           0        0    NaN  MnPrv
1457         Lvl    AllPub    Inside  ...           0        0    NaN  GdPrv
1458         Lvl    AllPub    Inside  ...           0        0    NaN    NaN
1459         Lvl    AllPub    Inside  ...           0        0    NaN    NaN

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition
0            NaN       0       2    2008        WD         Normal
1            NaN       0       5    2007        WD         Normal
2            NaN       0       9    2008        WD         Normal
3            NaN       0       2    2006        WD        Abnorml
4            NaN       0      12    2008        WD         Normal
...          ...     ...     ...     ...       ...            ...
1455         NaN       0       8    2007        WD         Normal
1456         NaN       0       2    2010        WD         Normal
1457        Shed    2500       5    2010        WD         Normal
1458         NaN       0       4    2010        WD         Normal
1459         NaN       0       6    2008        WD         Normal

[1460 rows x 79 columns]

In [7]:
df.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
Length: 79, dtype: object

In [8]:
cat_cols = [col for col in df.columns if df[col].dtype == "object"]
con_cols = [col for col in df.columns if df[col].dtype != "object"]

In [9]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [10]:
# x = df.drop(["SalePrice","Id"],axis= 1)

In [11]:
# y = df["SalePrice"]

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [14]:
x_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
254,20,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1066,60,RL,59.0,7837,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,5,2009,WD,Normal
638,30,RL,67.0,8777,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,5,2008,WD,Normal
799,50,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal
380,50,RL,50.0,5000,Pave,Pave,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,20,RL,78.0,9317,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,3,2007,WD,Normal
1130,50,RL,65.0,7804,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,12,2009,WD,Normal
1294,20,RL,60.0,8172,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
860,50,RL,55.0,7642,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal
1126,120,RL,53.0,3684,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal

In [15]:
x_train.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
Length: 79, dtype: object

In [16]:
for col in x_train.columns:
    if x_train[col].dtype == "object":
        x_train[col].fillna(value=x_train[col].mode()[0],inplace=True)
        x_test[col].fillna(value=x_train[col].mode()[0],inplace=True)
    if x_train[col].dtype != "object":
        x_train[col].fillna(value=x_train[col].mean(),inplace= True)
        x_test[col].fillna(value=x_train[col].mean(),inplace=True)

In [17]:
pd.set_option("display.max_rows",80)

In [18]:
x_test.isna().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
PoolQC           0
Fence            0
MiscFeature      0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
dtype: int64

In [19]:
con_cols

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [20]:
# x_train[]
oe = OneHotEncoder(handle_unknown="ignore")

for col in x_train[con_cols]:
    oe_train = oe.fit_transform(x_train[cat_cols])
    oe_test = oe.transform(x_test[cat_cols])

sc = StandardScaler()

for cols in x_train[con_cols]:
    # col
    oe_train_sc = sc.fit_transform(x_train[con_cols])
    oe_test_sc = sc.transform(x_test[con_cols])

In [31]:
# pd.DataFrame(oe_train)

                                                      0
0       (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
1       (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
2       (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
3       (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
4       (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 8)\t1.0\n ...
...                                                 ...
1163    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
1164    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
1165    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
1166    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...
1167    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 7)\t1.0\n ...

[1168 rows x 1 columns]